version: '3.1'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my_mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQLD_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - db_data:/var/lib/mysql



  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: .
    depends_on: 
      - db
    volumes:
      - ./app/src/main/java/urnaeletronica/BackEnd/Migration:/migrations
      - ./scripts:/scripts

    entrypoint: /scripts/entrypoint.sh
    
volumes:
  db_data: